name: GitHub workflow
on: push
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install -e .
      - run: |
          pip install pytest pytest-cov
          pytest --cov-report=xml
      - uses: codecov/codecov-action@v1
